import { IBM_Plex_Sans_JP } from "next/font/google";
import { Providers } from "./providers";
import Header from "./header";
import Main from "./main";

const ibmPlexSansJP = IBM_Plex_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Naoyuki Masuda - Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={ibmPlexSansJP.className}>
      <head></head>
      <body>
        <Providers>
          <Header />
          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  );
}
