import { Inter } from "next/font/google";
import { M_PLUS_Rounded_1c } from "next/font/google";
import { Providers } from "./providers";
import Header from "./header";
import Main from "./main";

const inter = Inter({ subsets: ["latin"] });

const Rounded = M_PLUS_Rounded_1c({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={Rounded.className}>
        <Providers>
          <Header />
          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  );
}
