import { Inter } from 'next/font/google'
import { Providers } from './providers';
import Header from "./header";
import Main from "./main";
import Footer from "./footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div>
      <h1>新着記事</h1>
      <ul>
        <li>記事1</li>
        <li>記事2</li>
        <li>記事3</li>
        <li>記事1</li>
        <li>記事2</li>
        <li>記事3</li>
        <li>記事1</li>
        <li>記事2</li>
        <li>記事3</li>
      </ul>
    </div>
          <Main>{children}</Main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
